### ISSUE TITLE
Modification matière

### ISSUE THREAD

**Issue by jjoelp** [Techzara/sekoly-numerika#1]
-Titre "Ajout nouveau matière" au lieu de "Modification matière"
-Bouton "Ajouter" plutôt "Modifier"

Je trouve aussi que c'est mieux d'utiliser plutôt le terme "Cours"
![capture d ecran 2018-12-28 a 14 21 11](https://user-images.githubusercontent.com/16410541/50514003-7d0a7200-0aac-11e9-85b5-0e2e2d8cc04a.png)

**Comment by julkwel** [comment]
Ok jerena daholo ireto

**Comment by julkwel** [comment]
Maj fait 
-Titre "Ajout nouveau matière" au lieu de "Modification matière"
-Bouton "Ajouter" plutôt "Modifier"

Je trouve aussi que c'est mieux d'utiliser plutôt le terme "Cours"
